[package]
name = "api"
version = "0.1.0"
edition = "2024"

[lib]
name = "api"
crate-type = ["cdylib"]

[dependencies]
fit-rust = { git = "https://github.com/vlegout/fit-rust.git", "branch" = "fix" }

[dependencies.pyo3]
version = "0.28.1"
features = ["abi3-py313"]
